model:
  target: cldm.toss.TOSS
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    control_key: "hint"
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    only_mid_control: False
    ucg_123: 0.5
    loss_weight: "eps"
    max_timesteps: 1000
    min_timesteps: 0
    finetune: True
    img_ucg: 0.05

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 100 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: cldm.toss.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        temp_attn: "CA"
        pose_enc: "freq"

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder


data800k:
  target: datasets.objaverse800k.ObjaverseDataModuleFromConfig
  params:
    root_dir: '/comp_robot/mm_generative/data/.objaverse/hf-objaverse-v1/views_release'
    batch_size: 160
    num_workers: 12
    total_view: 12
    caption: "rerank"
    pose_enc: "freq"
    train:
      validation: False
      image_transforms:
        size: 256

    validation:
      validation: True
      image_transforms:
        size: 256

data:
  target: datasets.objaverse.ObjaverseDataModuleFromConfig
  params:
    root_dir: '/comp_robot/mm_generative/data/.objaverse/hf-objaverse-v1/views_whole_sphere'
    batch_size: 128
    num_workers: 12
    total_view: 12
    caption: "rerank"
    train:
      validation: False
      image_transforms:
        size: 256

    validation:
      validation: True
      image_transforms:
        size: 256


data_car:
  target: datasets.objaverse_car.ObjaverseDataModuleFromConfig
  params:
    root_dir: '/comp_robot/mm_generative/data/.objaverse/hf-objaverse-v1/views_release'
    batch_size: 128
    num_workers: 12
    total_view: 12
    caption: 'rerank'
    pose_enc: "freq"
    train:
      validation: False
      image_transforms:
        size: 256

    validation:
      validation: True
      image_transforms:
        size: 256

srn_data:
  target: datasets.SRNDataset.SRNDataModuleFromConfig
  params:
    root_dir: '/comp_robot/mm_generative/data/nerf/srn_cars/'
    batch_size: 128
    num_workers: 16
    caption: "rerank"
    train:
      validation: False
      image_transforms:
        size: 256

    validation:
      validation: True
      image_transforms:
        size: 256

srn_chairs:
  target: datasets.SRNDataset_chairs.SRNDataModuleFromConfig
  params:
    root_dir: '/comp_robot/mm_generative/data/nerf/srn_chairs/'
    batch_size: 96
    num_workers: 16
    caption: "rerank"
    train:
      validation: False
      image_transforms:
        size: 256

    validation:
      validation: True
      image_transforms:
        size: 256